export const GET_ARTICLES = "GET_ARTICLES";
export const LOAD_ARTICLES = 'LOAD_ARTICLES'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_ERROR = 'LOAD_ARTICLES_ERROR'
export const POST_ARTICLES_SUCCESS = 'POST_ARTICLES_SUCCESS'
export const POST_ARTICLES_ERROR = 'POST_ARTICLES_ERROR'