export const POST_COMMENT_LOADING = "POST_COMMENT_LOADING";
export const POST_COMMENT_SUCCESS = "POST_COMMETNS_SUCCESS";
export const POST_COMMENT_ERROR = "POST_COMMETNS_ERROR";

export const DELETE_COMMENT_LOADING = "DELETE_COMMENT_LOADING";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const PUT_COMMENT_LOADING = "PUT_COMMENT_LOADING";
export const PUT_COMMENT_SUCCESS = "PUT_COMMENT_SUCCESS";
export const PUT_COMMENT_ERROR = "PUT_COMMENT_ERROR";

export const GET_COMMENTS_LOADING = "GET_COMMENTS_LOADING";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";
